### PR TITLE
Use the official drupal repository.

### PR DESCRIPTION
**Pull request by joshuataylor**
This uses the official drupal repository. Need discussion for this.

### CODE REVIEW

**Comment by jmolivas** [comment]
What do you guys think ? @dmouse @enzolutions @omero 
Should we use repo from drupal or github ?

**Comment by enzolutions** [comment]
Beta 7 is not supported yet right, I don't remember the original reason we didn't use at the begging was something related with travis @dmouse ?

**Comment by joshuataylor** [comment]
Actually... drupal/drupal is supported by packagist, and submitted by Dries.

https://packagist.org/packages/drupal/drupal

No reason not to use it?

**Comment by dmouse** [comment]
Yes, drupal/drupal is available on Packagist, drupal/drupal only have one dependency, this dependency is drupal/core. 

If you use the package drupal/drupal, you cloned all history of drupal only for read the composer.json

If you use the drupal/core you cloned the core directory with the vendor directory, this is unnecessary. 

For this reasons we have created the repo only with core directory without vendors.

**Comment by jmolivas** [comment]
I think we should update top Beta7, I am testing the commands and I am almost fix the issues I found => https://github.com/hechoendrupal/DrupalAppConsole/issues/455 and this change will be need it.

Related to use `drupal/core`, `drupal/drupal` or keep `hechoendrupal/drupal` I have not mush to say since @dmouse is how have been taking care of travis config.

**Comment by jmolivas** [comment]
Probably the downside keep using `hechoendrupal/drupal`is that we should maintain and tagging releases on the repo https://github.com/hechoendrupal/drupal on every `drupal/drupal` release

**Comment by webflo** [comment]
There is already a semi-official subtree split https://packagist.org/packages/drupal/core maintained by @tstoeckler. It is with vendor but this should not matter for your use-case.

**Comment by jmolivas** [comment]
@dmouse set it to `"drupal/core": "8.0.0-beta7"` I think this PR should me closed now what do you guys think about ? @dmouse @enzolutions @joshuataylor @webflo

**Comment by webflo** [comment]
Yup, its good.

**Pull request closed without merging**
